# Generated by Django 4.0.1 on 2022-04-08 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50)),
                ('bookSerialNumber', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('yearOfPublish', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('yearOfStudy', models.IntegerField()),
                ('numberOfStudents', models.IntegerField()),
                ('courseCode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('othername', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('idnumber', models.IntegerField(unique=True)),
                ('dateOfBirth', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('departmentId', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.course')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY')], max_length=10)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitName', models.CharField(max_length=200)),
                ('unitCode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('7:00-9:00', '7:00-9:00'), ('9:00-11:00', '9:00-11:00'), ('11:00-1:00', '11:00-1:00'), ('1:00-2:00', '1:00-2:00'), ('2:00-4:00', '2:00-4:00'), ('4:00-6:00', '4:00-6:00')], max_length=20)),
                ('room', models.CharField(max_length=10)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.timetableday')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.lecturer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.units')),
            ],
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('otherme', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('idnumber', models.IntegerField(blank=True, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('password', models.IntegerField(default=12345678)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('residence', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('avatar', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.staffdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('otherme', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('idnumber', models.IntegerField(blank=True, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('password', models.IntegerField(default=12345678)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('residence', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('avatar', models.CharField(max_length=200)),
                ('regNumber', models.SlugField(blank=True, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('likes', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('dateOfReturn', models.DateField()),
                ('bookBorrowed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.book')),
                ('issuedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.supportstaff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.student')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.department'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('commentedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.student')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
        ),
    ]
